// components/base/headline/headline.js
Component({
  properties:{
    level:{
      type:[Number,String],
      value:1
    },
    css:{
      type:String,
      value:''
    }
  },
  data:{
    styles:[
      'font-size:26px;',
      'font-size:18px;',
      'font-size:16px;',
      'font-size:14px;font-weight:400',
    ]
  }
})